; TODO '.cbor' control operator isn't supported by our validation lib at the moment.
;
; rule =
;   [ version                    ; The codec version used to encode the following event.
;   , bytes .cbor anchored-event ; An CBOR-encoded anchored ledger event.
;   ]

rule =
  ledger-event

anchored-event =
  { 0: block-header-hash       ; The block header hash from where this event was emitted.
  , 1: slot                    ; The slot number corresponding to the aforementioned header hash.
  , 2: ledger-event            ; The actual ledger event.
  }

; ============= ;
; Ledger events ;
; ============= ;

ledger-event =
  [  0, ledger-event.epoch
  // 1, ledger-event.body
  // 2, ledger-event.tick
  ]

ledger-event.epoch =
  [  0, epoch.mir-distribution
  // 1, epoch.stake-pool-reaping
  // 2, epoch.stake-distribution
  // 3, epoch.incremental-rewards
  // 4, epoch.delta-rewards
  // 5, epoch.restrained-rewards
  // 6, epoch.total-rewards
  // 7, epoch.starts-at
  ]

epoch.mir-distribution =
  ( stake-distribution ; Rewards paid from the Reserve into stake credentials
  , stake-distribution ; Rewards paid from the Treasury into stake credentials
  , delta-coin         ; Transfer from the Reserve into the Treasury
  , delta-coin         ; Transfer from the Treasury into the Reserve
  )

epoch.stake-pool-reaping =
  ( epoch
  , refund-distribution
  , refund-distribution
  )

epoch.stake-distribution =
  any

epoch.incremental-rewards =
  any

epoch.delta-rewards =
  any

epoch.restrained-rewards =
  any

epoch.total-rewards =
  any

epoch.starts-at =
  epoch

ledger-event.body =
  any

ledger-event.tick =
  any

; ============== ;
; Common schemas ;
; ============== ;

coin =
  uint

block-header-hash =
  $hash32

delta-coin =
  int

epoch =
  uint

pool-id =
  $hash28

refund-distribution =
  { * stake-credential => { * $hash28 => coin } }

reward =
  { 0: reward-type
  , 1: pool-id
  , 2: coin
  }

reward-type =
  [  0 ; member rewards
  // 1 ; leader rewards
  ]

slot =
  uint

stake-credential =
  [  0, $hash28   ; Key hash digest
  // 1, $hash28   ; Script hash digest
  ]

stake-distribution =
  { * stake-credential => coin
  }

version =
  uint

; ========================= ;
; Parameterized  primitives ;
; ========================= ;

$hash28 =
  bytes .size 28

$hash32 =
  bytes .size 32
